export const ResidentRejectTypeEnum = {
	DADOS_INCONSISTENTES: "DADOS_INCONSISTENTES",
	DOCUMENTO_INVALIDO: "DOCUMENTO_INVALIDO",
	INFORMACOES_INCOMPLETAS: "INFORMACOES_INCOMPLETAS",
	NAO_PERTENCE_AO_CONDOMINIO: "NAO_PERTENCE_AO_CONDOMINIO",
	OUTRO: "OUTRO",
} as const;

export type ResidentRejectTypeEnumType = keyof typeof ResidentRejectTypeEnum;

